# Run mode, either development or production. Production will use the GPIO pins.
mode: development

# Port and ip for the web server to listen on.
bind:
  port: 8000
  host: 127.0.0.1

# GPIO Configuration
gpio:
  # GPIO pin numbers for the optocouplers.
  pins:
    speed_1: 11
    speed_2: 12
    speed_3: 13
    away: 20
    auto: 21
    timer: 27
  # Backoff time between sending commands (in ms).
  backoff: 3000

mqtt:
  enabled: true
  client_id: ventilation
  discovery_prefix: homeassistant
  id: vent01
  url: mqtt://127.0.0.1:1883
  username: "test"
  password: "test"

# bcrypt hashed api keys.
# Use the following command to generate a new hash:
#  $ htpasswd -nbBC 10 "" <password> | tr -d ':\n'
api_keys:
  # Digest for the api key "test"
  - $2y$10$3lHF35DW58Cse5gtU9DBMukIcUkQNNclSk3SDLArd4g2/8xC12Qb2
  